name: trivia-app-unittest
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Set up AWS credentials
        uses: actions/setup-aws@v2
        with:
          aws-region: 'us-east-1'    
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -U -r back-end-python/gameactions/requirements.txt
          pip install -U -r back-end-python/tests/requirements.txt
      - name: Test with pytest
        run: 
            pytest back-end-python/tests/unit --junit-xml=unittests.xml --cov-report=xml --cov=gameactions --cov-branch        
